"""Tool name constants — verbatim from each tool's toolName.ts."""

BASH_TOOL_NAME = "Bash"
FILE_READ_TOOL_NAME = "Read"
FILE_WRITE_TOOL_NAME = "Write"
FILE_EDIT_TOOL_NAME = "Edit"
GLOB_TOOL_NAME = "Glob"
GREP_TOOL_NAME = "Grep"
AGENT_TOOL_NAME = "Agent"
LEGACY_AGENT_TOOL_NAME = "Task"
TASK_OUTPUT_TOOL_NAME = "TaskOutput"
TASK_STOP_TOOL_NAME = "TaskStop"
TASK_CREATE_TOOL_NAME = "TaskCreate"
TASK_GET_TOOL_NAME = "TaskGet"
TASK_UPDATE_TOOL_NAME = "TaskUpdate"
TASK_LIST_TOOL_NAME = "TaskList"
WEB_FETCH_TOOL_NAME = "WebFetch"
WEB_SEARCH_TOOL_NAME = "WebSearch"
TODO_WRITE_TOOL_NAME = "TodoWrite"
NOTEBOOK_EDIT_TOOL_NAME = "NotebookEdit"
ASK_USER_QUESTION_TOOL_NAME = "AskUserQuestion"
SKILL_TOOL_NAME = "Skill"
ENTER_PLAN_MODE_TOOL_NAME = "EnterPlanMode"
EXIT_PLAN_MODE_TOOL_NAME = "ExitPlanMode"
TOOL_SEARCH_TOOL_NAME = "ToolSearch"
SEND_MESSAGE_TOOL_NAME = "SendMessage"
CONFIG_TOOL_NAME = "Config"
ENTER_WORKTREE_TOOL_NAME = "EnterWorktree"
EXIT_WORKTREE_TOOL_NAME = "ExitWorktree"
LSP_TOOL_NAME = "LSP"
LIST_MCP_RESOURCES_TOOL_NAME = "ListMcpResourcesTool"
READ_MCP_RESOURCE_TOOL_NAME = "ReadMcpResourceTool"
SYNTHETIC_OUTPUT_TOOL_NAME = "StructuredOutput"
TEAM_CREATE_TOOL_NAME = "TeamCreate"
TEAM_DELETE_TOOL_NAME = "TeamDelete"
BRIEF_TOOL_NAME = "Brief"
SLEEP_TOOL_NAME = "Sleep"


# ── Tool sets (from tools.ts) ──
ALL_AGENT_DISALLOWED_TOOLS = frozenset([
    TASK_OUTPUT_TOOL_NAME,
    EXIT_PLAN_MODE_TOOL_NAME,
    ENTER_PLAN_MODE_TOOL_NAME,
    ASK_USER_QUESTION_TOOL_NAME,
    TASK_STOP_TOOL_NAME,
])

ASYNC_AGENT_ALLOWED_TOOLS = frozenset([
    FILE_READ_TOOL_NAME,
    WEB_SEARCH_TOOL_NAME,
    TODO_WRITE_TOOL_NAME,
    GREP_TOOL_NAME,
    WEB_FETCH_TOOL_NAME,
    GLOB_TOOL_NAME,
    BASH_TOOL_NAME,
    FILE_EDIT_TOOL_NAME,
    FILE_WRITE_TOOL_NAME,
    NOTEBOOK_EDIT_TOOL_NAME,
    SKILL_TOOL_NAME,
    SYNTHETIC_OUTPUT_TOOL_NAME,
    TOOL_SEARCH_TOOL_NAME,
    ENTER_WORKTREE_TOOL_NAME,
    EXIT_WORKTREE_TOOL_NAME,
])

COORDINATOR_MODE_ALLOWED_TOOLS = frozenset([
    AGENT_TOOL_NAME,
    TASK_STOP_TOOL_NAME,
    SEND_MESSAGE_TOOL_NAME,
    SYNTHETIC_OUTPUT_TOOL_NAME,
])
